repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.7
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [ python, pyi ]
        args: ["--fix"]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]
  
  # Running tests on commit
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: Run unit tests
  #       entry: pytest tests/unit
  #       language: system
  #       types: [ python ]
  #       pass_filenames: false
  #       always_run: true
